version: "3.8"
services:
    cisco:
        image: cisco
        build:
            context: ./app
            dockerfile: ./Dockerfile
        environment:
            NODE_ENV: production
        ports:
        - 3000:3000
        depends_on: 
        - db
        networks:
        - overlay
        
    nginx:
        container_name: "nginx"
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile
        depends_on:
            - cisco
        ports:
          - "80:80"
        volumes:
            - ./nginx-conf:/etc/nginx/conf.d
        deploy:
            placement:
                constraints:
                    - "node.role==manager"
        networks:
            - overlay
    db:
        image: postgres
        restart: always
        container_name: "cisco_postgres"
        environment:
            - HOSTNAME=cisco_postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - PGDATA=/tmp
        ports:
            - "5433:5432"
        volumes:
            - ./pg/db_data:/var/lib/postgresql/data
        networks:
            - overlay
networks:
  overlay: