version: "3.8"
services:
    nodeserver:
        build:
            context: ./main
        ports:
            - "3000:3000"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"
    app:
        build: .
        depends_on:
            - postrges
        environment:
        DATABASE_URL: postgres://postgres:password@postgres:5432/db
        NODE_ENV: production
        PORT: 3000
        ports:
            - "3000:3000"
        command: npm run dev  
        volumes:
            - .:/main/
            - /main/node_modules
    postrges:
        image: postgres:latest
        ports:
            - "35432:5432"
        environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: postgres_db
        
