version: "3.8"
services:
    nodeserver:
        build:
            context: ./main
            dockerfile: ./Dockerfile
        ports:
            - "3000:3000"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"
        links:
            - "db"
    db:
        image: "postgres:12"
        container_name: "postgres"
        environment:
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
        volumes:
            - ./pg/db_data:/var/lib/postgresql/data