version: "3.8"
services:
    app:
        container_name: "nodejs"
        build: .
        command: npm start
        volumes:
            - .:/usr/app/
            - /usr/app/node_modules
        ports: 
            - "3000:3000" 
        depends_on:
            - db
        networks:
            - overlay
        environment: 
            - DB_HOST=cisco_postgres
        
    nginx:
        container_name: "nginx"
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile
        depends_on:
            - app
        ports:
          - "80:80"
        volumes:
            - ./nginx-conf:/etc/nginx/conf.d
        deploy:
            placement:
                constraints:
                    - "node.role==manager"
        networks:
            - overlay
    db:
        image: postgres
        restart: always
        container_name: "cisco_postgres"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
        volumes:
            - ./pg/db_data:/var/lib/postgresql/data
        networks:
            - overlay
networks:
  overlay: